### ISSUE TITLE
no matching package named `couchbase-lite-core-sys` found

### ISSUE THREAD

**Issue by CedricCouton** [Dushistov/couchbase-lite-rust#41]
Hi,

I have a problem when I try to use the project as depencency like 
couchbase-lite = { git = "https://github.com/Dushistov/couchbase-lite-rust.git"}
The cargo build is ko with this error : `error: no matching package named `couchbase-lite-core-sys` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `couchbase-lite v0.3.1 (https://github.com/Dushistov/couchbase-lite-rust.git#ec6390bb)`
`
My cargo version is : cargo 1.45.1 

It seem to be linked with the couchbase-lite module and sys dependency : couchbase-lite-core-sys = "0.2.2", in the old version of the project the dependency was referenced with the relative path and my build was ok.
Do I miss something ?

Thanks

**Comment by Dushistov** [comment]
> dependency was referenced with the relative path 
The relative path cause some problems in long run, in some cases c++ dependency should
be rebuild, but `cargo` can not understand this, so version change of `couchbase-lite-core-sys`
works in more reliable way.

So you need reference both crates in your Cargo.toml,
for example in my project that uses couchbase-lite-rust I use:

```
couchbase-lite = { git = "https://github.com/Dushistov/couchbase-lite-rust", rev = "ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a" }
couchbase-lite-core-sys = { git = "https://github.com/Dushistov/couchbase-lite-rust", rev = "ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a" }
```

**Comment by CedricCouton** [comment]
If I try your solution I have this problem :
error: no matching package named `couchbase-lite-core-sys` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `couchbase-lite v0.3.1 (https://github.com/Dushistov/couchbase-lite-rust?rev=ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a#ec6390bb)`

my cargo.toml :
[dependencies]
couchbase-lite = { git = "https://github.com/Dushistov/couchbase-lite-rust", rev = "ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a" }
couchbase-lite-core-sys = { git = "https://github.com/Dushistov/couchbase-lite-rust", rev = "ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a" }

**Comment by Dushistov** [comment]
I forgot to say, this is not dependicies section,
it is `[patch.crates-io]` section: https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html

in dependency section you need only specify `couchbase-lite = version`

**Comment by CedricCouton** [comment]
Yes, and me I forgot to ask you if the patch section can solve the problem ^^.  So it solve it ^^, thanks!. The patch section of the couchbase-lite-rust is to be copied globally o is it automatically inherited?

**Comment by Dushistov** [comment]
If you mean this:
https://github.com/Dushistov/couchbase-lite-rust/blob/ec6390bbb36c47a9254b7a4fdb27b9b1feccc92a/Cargo.toml#L5

then no, it is not inherited.
But some lines may be unnecessary for you. For example cmake-rs patch required if you target iOS,
for other cases you can use not patched cmake-rs.

http and tungstenite are important if you use replication.
By the way tungstenite patches was accepted and included into new release,
so in the near future I will remove tungstenite from patch section.
http patch is still hanging though (https://github.com/hyperium/http/pull/422)

**Comment by CedricCouton** [comment]
Ok so as I use replication I must add those patch lines in my project until your patch are accepted.
Thanks !
